package health

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/require"
)

// Wire format of contracts/health/*.json, generated by `lake exe truth export`.

type wireEvent struct {
	Type     string `json:"type"`
	Unit     int    `json:"unit"`
	TS       int64  `json:"ts"`
	Health   string `json:"health"`
	Observer string `json:"observer"`
	Now      int64  `json:"now"`
}

type wireEntry struct {
	TS       int64  `json:"ts"`
	Health   string `json:"health"`
	Observer string `json:"observer"`
}

type wireExpect struct {
	OK       bool         `json:"ok"`
	View     []*wireEntry `json:"view"`
	Statuses []string     `json:"statuses"`
	Error    string       `json:"error"`
}

type vectors struct {
	SpecVersion string `json:"specVersion"`
	Traces      []struct {
		Name  string `json:"name"`
		Steps []struct {
			Event  wireEvent  `json:"event"`
			Expect wireExpect `json:"expect"`
		} `json:"steps"`
	} `json:"traces"`
	Convergence []struct {
		Name   string       `json:"name"`
		InboxA []wireEvent  `json:"inboxA"`
		InboxB []wireEvent  `json:"inboxB"`
		Split  int          `json:"split"`
		Expect []*wireEntry `json:"expect"`
	} `json:"convergence"`
}

type manifest struct {
	SpecVersion string           `json:"specVersion"`
	Constants   map[string]int64 `json:"constants"`
	Health      []string         `json:"health"`
	Observers   []string         `json:"observers"`
	Statuses    []string         `json:"statuses"`
	ErrorCodes  []string         `json:"errorCodes"`
}

// contractsDir honours CONTRACTS_DIR, otherwise walks up to the repository's contracts folder.
func contractsDir(t *testing.T) string {
	t.Helper()
	if d := os.Getenv("CONTRACTS_DIR"); d != "" {
		return d
	}
	dir, err := os.Getwd()
	require.NoError(t, err)
	for {
		c := filepath.Join(dir, "contracts")
		if st, err := os.Stat(c); err == nil && st.IsDir() {
			return c
		}
		parent := filepath.Dir(dir)
		require.NotEqual(t, dir, parent, "contracts folder not found; set CONTRACTS_DIR")
		dir = parent
	}
}

func load[T any](t *testing.T, name string) T {
	t.Helper()
	var v T
	raw, err := os.ReadFile(filepath.Join(contractsDir(t), "health", name))
	require.NoError(t, err)
	require.NoError(t, json.Unmarshal(raw, &v))
	return v
}

func toReport(w wireEvent) Report {
	return Report{Unit: w.Unit, TS: w.TS, Health: Health(w.Health), Observer: Observer(w.Observer)}
}

func toWire(v View) []*wireEntry {
	out := make([]*wireEntry, SiteUnits)
	for u := range out {
		if e := v.Entry(u); e.Present {
			out[u] = &wireEntry{e.Report.TS, string(e.Report.Health), string(e.Report.Observer)}
		}
	}
	return out
}

func deliver(inbox []wireEvent) View {
	var v View
	for _, w := range inbox {
		if next, err := v.Receive(toReport(w)); err == nil {
			v = next
		}
	}
	return v
}

// TestConformance replays every single-replica trace produced by the Lean specification.
func TestConformance(t *testing.T) {
	v := load[vectors](t, "vectors.json")
	require.NotEmpty(t, v.Traces)
	for _, tr := range v.Traces {
		t.Run(tr.Name, func(t *testing.T) {
			var view View
			for i, st := range tr.Steps {
				where := fmt.Sprintf("step %d %+v", i+1, st.Event)
				switch st.Event.Type {
				case "Report":
					next, err := view.Receive(toReport(st.Event))
					if !st.Expect.OK {
						var rejected *RejectedError
						require.ErrorAs(t, err, &rejected, where)
						require.Equal(t, st.Expect.Error, string(rejected.Code), where)
						require.Equal(t, view, next, where)
						continue
					}
					require.NoError(t, err, where)
					view = next
					require.Equal(t, st.Expect.View, toWire(view), where)
				case "Query":
					got := make([]string, SiteUnits)
					for u := range got {
						got[u] = string(view.Status(st.Event.Now, u))
					}
					require.Equal(t, st.Expect.Statuses, got, where)
				default:
					require.FailNow(t, "unknown event type", st.Event.Type)
				}
			}
		})
	}
}

// TestConvergence checks that delivery order, duplicates and anti-entropy
// never change the final view.
func TestConvergence(t *testing.T) {
	v := load[vectors](t, "vectors.json")
	require.NotEmpty(t, v.Convergence)
	for _, c := range v.Convergence {
		t.Run(c.Name, func(t *testing.T) {
			require.Equal(t, c.Expect, toWire(deliver(c.InboxA)), "replica A")
			require.Equal(t, c.Expect, toWire(deliver(c.InboxB)), "replica B")
			primary, standby := deliver(c.InboxA[:c.Split]), deliver(c.InboxA[c.Split:])
			require.Equal(t, c.Expect, toWire(primary.Merge(standby)), "merge primary <- standby")
			require.Equal(t, c.Expect, toWire(standby.Merge(primary)), "merge standby <- primary")
		})
	}
}

// TestGeneratedCodeMatchesManifest guards against a stale contract_gen.go.
func TestGeneratedCodeMatchesManifest(t *testing.T) {
	m := load[manifest](t, "manifest.json")
	require.Equal(t, SpecVersion, m.SpecVersion)
	require.Equal(t, map[string]int64{
		"siteUnits": int64(SiteUnits), "probeInterval": ProbeInterval, "probeTimeout": ProbeTimeout, "freshFor": FreshFor,
	}, m.Constants)
	require.Equal(t, m.Health, names(AllHealth))
	require.Equal(t, m.Observers, names(AllObservers))
	require.Equal(t, m.Statuses, names(AllStatuses))
	require.Equal(t, m.ErrorCodes, names(AllErrorCodes))
}

func names[T ~string](xs []T) []string {
	out := make([]string, len(xs))
	for i, x := range xs {
		out[i] = string(x)
	}
	return out
}
