// Code generated by `lake exe truth export` from lean/Truth/Health/Spec.lean (spec 1.0.0). DO NOT EDIT.
// Change the Lean specification and run `task contracts`.

package health

// Health is a probe result, ordered by severity (worse is greater).
type Health string

const (
	HealthHealthy   Health = "Healthy"
	HealthDegraded  Health = "Degraded"
	HealthUnhealthy Health = "Unhealthy"
)

// AllHealth lists every Health value in specification order.
var AllHealth = []Health{HealthHealthy, HealthDegraded, HealthUnhealthy}

// Observer is the platform instance that produced a report.
type Observer string

const (
	ObserverPrimary Observer = "Primary"
	ObserverStandby Observer = "Standby"
)

// AllObservers lists every Observer value in specification order.
var AllObservers = []Observer{ObserverPrimary, ObserverStandby}

// Status is what an operator console shows for a unit.
type Status string

const (
	StatusHealthy   Status = "Healthy"
	StatusDegraded  Status = "Degraded"
	StatusUnhealthy Status = "Unhealthy"
	StatusUnknown   Status = "Unknown"
)

// AllStatuses lists every Status value in specification order.
var AllStatuses = []Status{StatusHealthy, StatusDegraded, StatusUnhealthy, StatusUnknown}

// ErrorCode says why a report was rejected.
type ErrorCode string

const (
	ErrUnknownUnit ErrorCode = "UnknownUnit"
)

// AllErrorCodes lists every ErrorCode value in specification order.
var AllErrorCodes = []ErrorCode{ErrUnknownUnit}

// SpecVersion is the version of the Lean specification this file was generated from.
const SpecVersion = "1.0.0"

// SiteUnits is the number of service units at the site, identical on every instance.
const SiteUnits int = 4

// ProbeInterval is the number of seconds between two probes of a unit.
const ProbeInterval int64 = 10

// ProbeTimeout is the number of seconds a probe may take.
const ProbeTimeout int64 = 3

// FreshFor is the number of seconds a report stays evidence: 2 * probeInterval + probeTimeout.
const FreshFor int64 = 23
