package zone

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/require"
)

// Wire format of contracts/zone/*.json, generated by `lake exe truth export`.

type wireEvent struct {
	Type       string `json:"type"`
	TS         int64  `json:"ts"`
	Lat        int64  `json:"lat"`
	Lon        int64  `json:"lon"`
	Authorized bool   `json:"authorized"`
	Now        int64  `json:"now"`
}

type wireExpect struct {
	OK         bool   `json:"ok"`
	Alarm      string `json:"alarm"`
	Inside     bool   `json:"inside"`
	Lost       bool   `json:"lost"`
	Authorized bool   `json:"authorized"`
	LastTS     int64  `json:"lastTs"`
	Error      string `json:"error"`
}

type vectors struct {
	SpecVersion string `json:"specVersion"`
	Traces      []struct {
		Name  string `json:"name"`
		Steps []struct {
			Event  wireEvent  `json:"event"`
			Expect wireExpect `json:"expect"`
		} `json:"steps"`
	} `json:"traces"`
}

type manifest struct {
	SpecVersion string           `json:"specVersion"`
	Constants   map[string]int64 `json:"constants"`
	AlarmStates []string         `json:"alarmStates"`
	ErrorCodes  []string         `json:"errorCodes"`
}

// contractsDir honours CONTRACTS_DIR, otherwise walks up to the repository's contracts folder.
func contractsDir(t *testing.T) string {
	t.Helper()
	if d := os.Getenv("CONTRACTS_DIR"); d != "" {
		return d
	}
	dir, err := os.Getwd()
	require.NoError(t, err)
	for {
		c := filepath.Join(dir, "contracts")
		if st, err := os.Stat(c); err == nil && st.IsDir() {
			return c
		}
		parent := filepath.Dir(dir)
		require.NotEqual(t, dir, parent, "contracts folder not found; set CONTRACTS_DIR")
		dir = parent
	}
}

func load[T any](t *testing.T, name string) T {
	t.Helper()
	var v T
	raw, err := os.ReadFile(filepath.Join(contractsDir(t), "zone", name))
	require.NoError(t, err)
	require.NoError(t, json.Unmarshal(raw, &v))
	return v
}

func toEvent(t *testing.T, w wireEvent) Event {
	t.Helper()
	switch w.Type {
	case "Report":
		return Report{TS: w.TS, Lat: w.Lat, Lon: w.Lon}
	case "Acknowledge":
		return Acknowledge{}
	case "Authorize":
		return Authorize{Authorized: w.Authorized}
	case "Tick":
		return Tick{Now: w.Now}
	}
	require.FailNow(t, "unknown event type", w.Type)
	return nil
}

// TestConformance replays every trace produced by the Lean specification.
func TestConformance(t *testing.T) {
	v := load[vectors](t, "vectors.json")
	require.NotEmpty(t, v.Traces)
	for _, tr := range v.Traces {
		t.Run(tr.Name, func(t *testing.T) {
			track := NewTrack()
			for i, st := range tr.Steps {
				where := fmt.Sprintf("step %d %+v", i+1, st.Event)
				next, err := track.Apply(toEvent(t, st.Event))
				if !st.Expect.OK {
					var rejected *RejectedError
					require.ErrorAs(t, err, &rejected, where)
					require.Equal(t, st.Expect.Error, string(rejected.Code), where)
					require.Equal(t, track, next, "%s: a rejected message must not change the track", where)
					continue
				}
				require.NoError(t, err, where)
				track = next
				got := wireExpect{true, string(track.Alarm), track.Inside, track.Lost, track.Authorized, track.LastTS, ""}
				require.Equal(t, st.Expect, got, where)
			}
		})
	}
}

// TestGeneratedCodeMatchesManifest guards against a stale contract_gen.go.
func TestGeneratedCodeMatchesManifest(t *testing.T) {
	m := load[manifest](t, "manifest.json")
	v := load[vectors](t, "vectors.json")
	require.Equal(t, SpecVersion, m.SpecVersion)
	require.Equal(t, SpecVersion, v.SpecVersion)
	require.Equal(t, map[string]int64{
		"unitsPerDegree": UnitsPerDegree, "maxLat": MaxLat, "maxLon": MaxLon,
		"latNotAvailable": LatNotAvailable, "lonNotAvailable": LonNotAvailable,
		"zoneLatMin": ZoneLatMin, "zoneLatMax": ZoneLatMax, "zoneLonMin": ZoneLonMin, "zoneLonMax": ZoneLonMax,
		"staleAfter": StaleAfter,
	}, m.Constants)
	require.Equal(t, m.AlarmStates, names(AllAlarmStates))
	require.Equal(t, m.ErrorCodes, names(AllErrorCodes))
}

func TestUnsupportedEventIsSystemError(t *testing.T) {
	_, err := NewTrack().Apply(nil)
	require.Error(t, err)
	var rejected *RejectedError
	require.False(t, errors.As(err, &rejected))
}

func names[T ~string](xs []T) []string {
	out := make([]string, len(xs))
	for i, x := range xs {
		out[i] = string(x)
	}
	return out
}
