// Code generated by `lake exe truth export` from lean/Truth/Zone/Spec.lean (spec 1.0.0). DO NOT EDIT.
// Change the Lean specification and run `task contracts`.

package zone

// AlarmState is the alarm lifecycle state (IEC 62682 style). Values are the wire format.
type AlarmState string

const (
	AlarmNormal       AlarmState = "Normal"
	AlarmUnackActive  AlarmState = "UnackActive"
	AlarmAckActive    AlarmState = "AckActive"
	AlarmUnackCleared AlarmState = "UnackCleared"
)

// AllAlarmStates lists every AlarmState value in specification order.
var AllAlarmStates = []AlarmState{AlarmNormal, AlarmUnackActive, AlarmAckActive, AlarmUnackCleared}

// ErrorCode says why a message was rejected.
type ErrorCode string

const (
	ErrPositionUnavailable  ErrorCode = "PositionUnavailable"
	ErrInvalidPosition      ErrorCode = "InvalidPosition"
	ErrStaleReport          ErrorCode = "StaleReport"
	ErrNothingToAcknowledge ErrorCode = "NothingToAcknowledge"
)

// AllErrorCodes lists every ErrorCode value in specification order.
var AllErrorCodes = []ErrorCode{ErrPositionUnavailable, ErrInvalidPosition, ErrStaleReport, ErrNothingToAcknowledge}

// SpecVersion is the version of the Lean specification this file was generated from.
const SpecVersion = "1.0.0"

// UnitsPerDegree is the number of AIS position units (1/10 000 minute) per degree.
const UnitsPerDegree int64 = 600000

// MaxLat is the largest valid latitude (90 degrees) in AIS units.
const MaxLat int64 = 54000000

// MaxLon is the largest valid longitude (180 degrees) in AIS units.
const MaxLon int64 = 108000000

// LatNotAvailable is the AIS marker for latitude not available (91 degrees).
const LatNotAvailable int64 = 54600000

// LonNotAvailable is the AIS marker for longitude not available (181 degrees).
const LonNotAvailable int64 = 108600000

// ZoneLatMin is the southern boundary of the safety zone, inclusive.
const ZoneLatMin int64 = 35097300

// ZoneLatMax is the northern boundary of the safety zone, inclusive.
const ZoneLatMax int64 = 35102700

// ZoneLonMin is the western boundary of the safety zone, inclusive.
const ZoneLonMin int64 = 1194800

// ZoneLonMax is the eastern boundary of the safety zone, inclusive.
const ZoneLonMax int64 = 1205200

// StaleAfter is the number of seconds without a report after which a track is lost.
const StaleAfter int64 = 180
