version: "3"

tasks:
  feline-build:
    desc: "Build the feline project"
    dir: ./feline
    cmds:
      - lake build

  greeting-run:
    desc: "Run the greeting project"
    dir: ./greeting
    cmds:
      - lake exe greeting
