import Truth.Order.Spec
import Truth.Export.Json

/-!
# Code & documentation generation

"Shape" (names, enums, constants) flows **from** the spec **into** code,
so teams never retype it. "Behaviour" is hand-written by teams and
checked by the conformance vectors.
-/

namespace Truth.Export
open Truth.Order

def header (commentPrefix : String) : String :=
  s!"{commentPrefix} Generated by `lake exe truth export` from lean/Truth/Order/Spec.lean (spec {specVersion}).\n" ++
  s!"{commentPrefix} DO NOT EDIT. Change the Lean specification and run `task contracts`.\n"

def padRight (s : String) (n : Nat) : String := s.pushn ' ' (n - s.length)

def maxLen (xs : List String) : Nat := xs.foldl (fun m s => max m s.length) 0

/-! ## Manifest (machine-readable summary of the vocabulary) -/

def manifestJson : Json :=
  .obj [
    ("specVersion", .str specVersion),
    ("constants", .obj [
      ("approvalThreshold", .num approvalThreshold),
      ("maxLines", .num maxLines),
      ("maxQty", .num maxQty),
      ("maxUnitPrice", .num maxUnitPrice)]),
    ("statuses", .arr (Status.all.map (.str ·.name))),
    ("errorCodes", .arr (ErrorCode.all.map (.str ·.name))),
    ("events", .arr [
      .obj [("type", .str "AddLine"), ("fields", .arr [.str "sku", .str "qty", .str "unitPrice"])],
      .obj [("type", .str "Submit")], .obj [("type", .str "Approve")], .obj [("type", .str "Reject")],
      .obj [("type", .str "Ship")], .obj [("type", .str "Cancel")]])
  ]

/-! ## C# -/

def csharp : String :=
  let enumBody (xs : List String) := ",\n".intercalate (xs.map ("    " ++ ·))
  "// <auto-generated>\n" ++ header "//" ++ "// </auto-generated>\n\n" ++
  "namespace Orders;\n\n" ++
  "/// <summary>Order lifecycle states (canonical names are the wire format).</summary>\n" ++
  s!"public enum OrderStatus\n\{\n{enumBody (Status.all.map Status.name)}\n}\n\n" ++
  "/// <summary>Business error codes returned when a command is rejected.</summary>\n" ++
  s!"public enum ErrorCode\n\{\n{enumBody (ErrorCode.all.map ErrorCode.name)}\n}\n\n" ++
  "/// <summary>Policy constants. Amounts are in minor units (cents).</summary>\n" ++
  "public static class Policy\n{\n" ++
  s!"    public const string SpecVersion = \"{specVersion}\";\n" ++
  s!"    public const long ApprovalThreshold = {approvalThreshold};\n" ++
  s!"    public const int MaxLines = {maxLines};\n" ++
  s!"    public const int MaxQty = {maxQty};\n" ++
  s!"    public const long MaxUnitPrice = {maxUnitPrice};\n" ++
  "}\n"

/-! ## Go -/

def goConstBlock (typ : String) (namePrefix : String) (xs : List String) : String :=
  let names := xs.map (namePrefix ++ ·)
  let w := maxLen names
  "const (\n" ++
  String.join ((names.zip xs).map fun (n, v) => s!"\t{padRight n w} {typ} = \"{v}\"\n") ++
  ")\n"

def goSlice (name typ : String) (items : List String) : String :=
  s!"var {name} = []{typ}" ++ "{" ++ ", ".intercalate items ++ "}\n\n"

def golang : String :=
  -- Go tooling recognises generated files by the "// Code generated ... DO NOT EDIT." line.
  s!"// Code generated by `lake exe truth export` from lean/Truth/Order/Spec.lean (spec {specVersion}). DO NOT EDIT.\n" ++
  "// Change the Lean specification and run `task contracts`.\n\npackage orders\n\n" ++
  "// SpecVersion is the version of the Lean specification this file was generated from.\n" ++
  s!"const SpecVersion = \"{specVersion}\"\n\n" ++
  "// Status is an order lifecycle state (canonical names are the wire format).\n" ++
  "type Status string\n\n" ++
  goConstBlock "Status" "Status" (Status.all.map Status.name) ++ "\n" ++
  "// AllStatuses lists every status in specification order.\n" ++
  goSlice "AllStatuses" "Status" (Status.all.map ("Status" ++ ·.name)) ++
  "// ErrorCode is a business error returned when a command is rejected.\n" ++
  "type ErrorCode string\n\n" ++
  goConstBlock "ErrorCode" "Err" (ErrorCode.all.map ErrorCode.name) ++ "\n" ++
  "// AllErrorCodes lists every error code in specification order.\n" ++
  goSlice "AllErrorCodes" "ErrorCode" (ErrorCode.all.map ("Err" ++ ·.name)) ++
  "// Policy constants. Amounts are in minor units (cents).\n" ++
  s!"const ApprovalThreshold int64 = {approvalThreshold}\n\n" ++
  s!"const MaxLines = {maxLines}\n\n" ++
  s!"const MaxQty int64 = {maxQty}\n\n" ++
  s!"const MaxUnitPrice int64 = {maxUnitPrice}\n"

/-! ## Documentation: the state machine, derived by *running* the spec -/

def money (cents : Nat) : String :=
  let c := cents % 100
  s!"{cents / 100}.{if c < 10 then "0" else ""}{c}"

/-- Representative orders per status: one small, one large (above threshold). -/
def samples (s : Status) : List (String × Order) :=
  [ (s!"total ≤ {money approvalThreshold}", { status := s, lines := [⟨"S", 1, 100⟩], approved := false }),
    (s!"total > {money approvalThreshold}", { status := s, lines := [⟨"L", 1, approvalThreshold + 1⟩], approved := false }) ]

def sampleEvents : List Event := [.addLine "X" 1 100, .submit, .approve, .reject, .ship, .cancel]

def outcome (o : Order) (e : Event) : String :=
  match step o e with
  | .ok o' => o'.status.name
  | .error err => s!"✗ {err.name}"

def mermaid : String := Id.run do
  let mut edges : List String := []
  for s in Status.all do
    for e in sampleEvents do
      let outs := (samples s).map fun (guard, o) => (guard, step o e)
      let same := match outs with
        | [(_, .ok a), (_, .ok b)] => a.status == b.status
        | _ => true
      for (guard, r) in outs do
        if let .ok o' := r then
          let label := if same then e.kind else s!"{e.kind} [{guard}]"
          let edge := s!"    {s.name} --> {o'.status.name} : {label}"
          if !edges.contains edge then edges := edges ++ [edge]
  return "```mermaid\nstateDiagram-v2\n    [*] --> Draft\n" ++ "\n".intercalate edges ++
    "\n    Shipped --> [*]\n    Cancelled --> [*]\n```\n"

def transitionTable : String :=
  let hdr := "| State | " ++ " | ".intercalate (sampleEvents.map Event.kind) ++ " |\n" ++
             "|---|" ++ String.join (sampleEvents.map fun _ => "---|") ++ "\n"
  hdr ++ String.join (Status.all.map fun s =>
    let cells := sampleEvents.map fun e =>
      let outs := ((samples s).map fun (_, o) => outcome o e).eraseDups
      " / ".intercalate outs
    s!"| **{s.name}** | " ++ " | ".intercalate cells ++ " |\n")

def stateMachineDoc : String :=
  s!"<!-- Generated by `lake exe truth export` from lean/Truth/Order/Spec.lean (spec {specVersion}). " ++
  "DO NOT EDIT. Change the Lean specification and run `task contracts`. -->\n\n" ++
  s!"# Order state machine (spec {specVersion})\n\n" ++
  "!!! info \"Generated from the specification\"\n" ++
  "    This page is produced by *executing* `step` from `lean/Truth/Order/Spec.lean` on\n" ++
  "    representative orders. It cannot drift from the truth: CI regenerates it and fails on any diff.\n\n" ++
  "## Diagram\n\n" ++ mermaid ++ "\n" ++
  "## Transition table\n\n" ++
  s!"Where two outcomes are shown, the first is for a small order (total ≤ {money approvalThreshold})," ++
  " the second for a large one.\n\n" ++ transitionTable ++ "\n" ++
  "## Policy constants\n\n" ++
  "| Constant | Value |\n|---|---|\n" ++
  s!"| `approvalThreshold` | {approvalThreshold} ({money approvalThreshold}) |\n" ++
  s!"| `maxLines` | {maxLines} |\n| `maxQty` | {maxQty} |\n" ++
  s!"| `maxUnitPrice` | {maxUnitPrice} ({money maxUnitPrice}) |\n\n" ++
  "## Error codes\n\n" ++ String.join (ErrorCode.all.map fun e => s!"- `{e.name}`\n")

end Truth.Export
