import Truth.Export.Json

/-!
# Shared exporter helpers: deterministic PRNG and code generation snippets
-/

namespace Truth.Export

/-! ## Deterministic pseudo-random numbers -/

structure Rng where
  state : UInt64
  deriving Inhabited

/-- 64-bit LCG (Knuth MMIX constants). Good enough for test generation and
identical on every platform, so vectors are reproducible. -/
def Rng.next (r : Rng) : Nat × Rng :=
  let s := r.state * 6364136223846793005 + 1442695040888963407
  ((s >>> 33).toNat, ⟨s⟩)

def Rng.below (r : Rng) (n : Nat) : Nat × Rng :=
  let (x, r) := r.next
  (x % n, r)

def Rng.pick {α} [Inhabited α] (r : Rng) (xs : List α) : α × Rng :=
  let (i, r) := r.below xs.length
  (xs[i]!, r)

/-! ## Headers -/

def source (spec : String) : String := s!"lean/Truth/{spec}/Spec.lean"

def csHeader (spec version : String) : String :=
  "// <auto-generated>\n" ++
  s!"// Generated by `lake exe truth export` from {source spec} (spec {version}).\n" ++
  "// DO NOT EDIT. Change the Lean specification and run `task contracts`.\n" ++
  "// </auto-generated>\n\n"

/-- Go tooling recognises generated files by the "// Code generated ... DO NOT EDIT." line. -/
def goHeader (spec version pkg : String) : String :=
  s!"// Code generated by `lake exe truth export` from {source spec} (spec {version}). DO NOT EDIT.\n" ++
  "// Change the Lean specification and run `task contracts`.\n\n" ++
  s!"package {pkg}\n\n"

def mdHeader (spec version : String) : String :=
  s!"<!-- Generated by `lake exe truth export` from {source spec} (spec {version}). " ++
  "DO NOT EDIT. Change the Lean specification and run `task contracts`. -->\n\n"

/-! ## C# -/

def csEnum (name doc : String) (members : List String) : String :=
  s!"/// <summary>{doc}</summary>\npublic enum {name}\n" ++ "{\n" ++
  ",\n".intercalate (members.map fun m => s!"    /// <summary>Wire value \"{m}\".</summary>\n    {m}") ++
  "\n}\n\n"

/-- A generated constant: type per language, name, value and documentation. -/
structure Const where
  name : String
  value : String
  doc : String
  csType : String := "long"
  goType : String := "int64"

def csPolicy (version : String) (consts : List Const) : String :=
  "/// <summary>Policy constants of the specification.</summary>\npublic static class Policy\n{\n" ++
  "    /// <summary>Version of the Lean specification this file was generated from.</summary>\n" ++
  s!"    public const string SpecVersion = \"{version}\";\n" ++
  String.join (consts.map fun c =>
    s!"\n    /// <summary>{c.doc.capitalize}</summary>\n    public const {c.csType} {c.name} = {c.value};\n") ++
  "}\n"

/-! ## Go -/

def padRight (s : String) (n : Nat) : String := s.pushn ' ' (n - s.length)

/-- A string-typed enum: type, const block, and an `All...` slice in spec order. -/
def goEnum (typ doc namePrefix allName : String) (members : List String) : String :=
  let names := members.map (namePrefix ++ ·)
  let w := names.foldl (fun m s => max m s.length) 0
  s!"// {typ} {doc}\ntype {typ} string\n\n" ++
  "const (\n" ++
  String.join ((names.zip members).map fun (n, v) => s!"\t{padRight n w} {typ} = \"{v}\"\n") ++
  ")\n\n" ++
  s!"// {allName} lists every {typ} value in specification order.\n" ++
  s!"var {allName} = []{typ}" ++ "{" ++ ", ".intercalate names ++ "}\n\n"

/-- Each constant is its own declaration so gofmt never realigns the block. -/
def goPolicy (version : String) (consts : List Const) : String :=
  "// SpecVersion is the version of the Lean specification this file was generated from.\n" ++
  s!"const SpecVersion = \"{version}\"\n" ++
  String.join (consts.map fun c => s!"\n// {c.name} is {c.doc}\nconst {c.name} {c.goType} = {c.value}\n")

/-! ## Markdown -/

def mdTable (header : List String) (rows : List (List String)) : String :=
  "| " ++ " | ".intercalate header ++ " |\n" ++
  "|" ++ String.join (header.map fun _ => "---|") ++ "\n" ++
  String.join (rows.map fun r => "| " ++ " | ".intercalate r ++ " |\n")

end Truth.Export
