package orders

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"testing"
)

// Wire format of contracts/order/*.json (generated by `lake exe truth export`).

type wireEvent struct {
	Type      string `json:"type"`
	SKU       string `json:"sku"`
	Qty       int64  `json:"qty"`
	UnitPrice int64  `json:"unitPrice"`
}

type wireExpect struct {
	OK       bool   `json:"ok"`
	Status   string `json:"status"`
	Total    int64  `json:"total"`
	Lines    int    `json:"lines"`
	Approved bool   `json:"approved"`
	Error    string `json:"error"`
}

type vectors struct {
	SpecVersion string `json:"specVersion"`
	Traces      []struct {
		Name  string `json:"name"`
		Steps []struct {
			Event  wireEvent  `json:"event"`
			Expect wireExpect `json:"expect"`
		} `json:"steps"`
	} `json:"traces"`
}

type manifest struct {
	SpecVersion string           `json:"specVersion"`
	Constants   map[string]int64 `json:"constants"`
	Statuses    []string         `json:"statuses"`
	ErrorCodes  []string         `json:"errorCodes"`
}

// contractsDir honours CONTRACTS_DIR, otherwise walks up to the repo's contracts/ folder.
func contractsDir(t *testing.T) string {
	if d := os.Getenv("CONTRACTS_DIR"); d != "" {
		return d
	}
	dir, _ := os.Getwd()
	for {
		c := filepath.Join(dir, "contracts")
		if st, err := os.Stat(c); err == nil && st.IsDir() {
			return c
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			t.Fatal("contracts/ not found; set CONTRACTS_DIR")
		}
		dir = parent
	}
}

func load[T any](t *testing.T, name string) T {
	t.Helper()
	var v T
	raw, err := os.ReadFile(filepath.Join(contractsDir(t), "order", name))
	if err == nil {
		err = json.Unmarshal(raw, &v)
	}
	if err != nil {
		t.Fatal(errors.Join(fmt.Errorf("loading %s", name), err))
	}
	return v
}

func toEvent(w wireEvent) Event {
	switch w.Type {
	case "AddLine":
		return AddLine{w.SKU, w.Qty, w.UnitPrice}
	case "Submit":
		return Submit{}
	case "Approve":
		return Approve{}
	case "Reject":
		return Reject{}
	case "Ship":
		return Ship{}
	case "Cancel":
		return Cancel{}
	}
	panic("unknown event type " + w.Type)
}

// TestConformance replays every trace produced by the Lean specification.
func TestConformance(t *testing.T) {
	v := load[vectors](t, "vectors.json")
	for _, tr := range v.Traces {
		t.Run(tr.Name, func(t *testing.T) {
			o := New()
			for i, st := range tr.Steps {
				ev := toEvent(st.Event)
				next, errCode := o.Apply(ev)
				where := fmt.Sprintf("step %d (%s %+v)", i+1, ev.kind(), st.Event)
				exp := st.Expect
				if exp.OK {
					if errCode != nil {
						t.Fatalf("%s: spec accepts, implementation rejected with %s", where, *errCode)
					}
					o = next
					got := wireExpect{true, string(o.Status), o.Total(), len(o.Lines), o.Approved, ""}
					if got != exp {
						t.Fatalf("%s:\n  spec: %+v\n  impl: %+v", where, exp, got)
					}
				} else {
					if errCode == nil {
						t.Fatalf("%s: spec rejects with %s, implementation accepted", where, exp.Error)
					}
					if string(*errCode) != exp.Error {
						t.Fatalf("%s: spec error %s, implementation error %s", where, exp.Error, *errCode)
					}
				}
			}
		})
	}
}

// TestGeneratedCodeMatchesManifest guards against a stale contract_gen.go.
func TestGeneratedCodeMatchesManifest(t *testing.T) {
	m := load[manifest](t, "manifest.json")
	v := load[vectors](t, "vectors.json")
	if m.SpecVersion != SpecVersion || v.SpecVersion != SpecVersion {
		t.Fatalf("spec version mismatch: code %s, manifest %s, vectors %s", SpecVersion, m.SpecVersion, v.SpecVersion)
	}
	consts := map[string]int64{
		"approvalThreshold": ApprovalThreshold, "maxLines": MaxLines, "maxQty": MaxQty, "maxUnitPrice": MaxUnitPrice,
	}
	for k, want := range m.Constants {
		if consts[k] != want {
			t.Errorf("constant %s: manifest %d, code %d", k, want, consts[k])
		}
	}
	if statuses := names(AllStatuses); !slices.Equal(statuses, m.Statuses) {
		t.Errorf("statuses: manifest %v, code %v", m.Statuses, statuses)
	}
	if codes := names(AllErrorCodes); !slices.Equal(codes, m.ErrorCodes) {
		t.Errorf("error codes: manifest %v, code %v", m.ErrorCodes, codes)
	}
}

func names[T ~string](xs []T) []string {
	out := make([]string, len(xs))
	for i, x := range xs {
		out[i] = string(x)
	}
	return out
}
