// Code generated by `lake exe truth export` from lean/Truth/Order/Spec.lean (spec 1.0.0). DO NOT EDIT.
// Change the Lean specification and run `task contracts`.

package orders

// SpecVersion is the version of the Lean specification this file was generated from.
const SpecVersion = "1.0.0"

// Status is an order lifecycle state (canonical names are the wire format).
type Status string

const (
	StatusDraft           Status = "Draft"
	StatusPendingApproval Status = "PendingApproval"
	StatusApproved        Status = "Approved"
	StatusShipped         Status = "Shipped"
	StatusCancelled       Status = "Cancelled"
)

// AllStatuses lists every status in specification order.
var AllStatuses = []Status{StatusDraft, StatusPendingApproval, StatusApproved, StatusShipped, StatusCancelled}

// ErrorCode is a business error returned when a command is rejected.
type ErrorCode string

const (
	ErrInvalidQuantity   ErrorCode = "InvalidQuantity"
	ErrInvalidPrice      ErrorCode = "InvalidPrice"
	ErrTooManyLines      ErrorCode = "TooManyLines"
	ErrEmptyOrder        ErrorCode = "EmptyOrder"
	ErrInvalidTransition ErrorCode = "InvalidTransition"
)

// AllErrorCodes lists every error code in specification order.
var AllErrorCodes = []ErrorCode{ErrInvalidQuantity, ErrInvalidPrice, ErrTooManyLines, ErrEmptyOrder, ErrInvalidTransition}

// Policy constants. Amounts are in minor units (cents).
const ApprovalThreshold int64 = 1000000

const MaxLines = 10

const MaxQty int64 = 10000

const MaxUnitPrice int64 = 100000000
